src/objects/Home_Improvement__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Home Improvements</relationshipLabel>
        <relationshipName>Home_Improvements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Home Improvement</label>
    <nameField>
        <label>Home Improvement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Home Improvements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Property__c.object
<CustomObject>
    <fields>
        <fullName>Business__c</fullName>
        <description>Business company or vendor renting the property</description>
        <label>Business</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SUM_of_Improvements__c</fullName>
        <label>SUM of Improvements</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/HomeImprovRollUpSumTest.cls
/**
 * Created by Asel on 4/1/20.
 */

@IsTest
private class HomeImprovRollUpSumTest {

    @IsTest
    static void testRollUpSum() {

        Property__c property = new Property__c();
        property.Name = 'Prop1';
        property.Business__c = 'Gov';
        property.SUM_of_Improvements__c = null;
        insert property;


        Home_Improvement__c homeImprovement = new Home_Improvement__c();
        homeImprovement.Name = 'HomeImpr';
        homeImprovement.Amount__c = 1000;
        homeImprovement.Property__c = property.Id;


        Test.startTest();

        insert homeImprovement;
        delete homeImprovement;

        Test.stopTest();


        Property__c propAfterInsert = [SELECT SUM_of_Improvements__c FROM Property__c WHERE Id =: property.Id];
        System.assertEquals(0, propAfterInsert.SUM_of_Improvements__c);

    }
}