src/objects/Home_Improvement__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Home Improvements</relationshipLabel>
        <relationshipName>Home_Improvements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Home Improvement</label>
    <nameField>
        <label>Home Improvement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Home Improvements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Property__c.object
<CustomObject>
    <fields>
        <fullName>SUM_of_Improvements__c</fullName>
        <label>SUM of Improvements</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/HomeImprovementRollUpSum.cls
/**
 * Created by Asel on 3/31/20.
 */
public class HomeImprovementRollUpSum {

    public static void newHandler(List<Home_Improvement__c> homeImprovements) {

        List<Id> ids = new List<Id>();
        List<Property__c> properties = new List<Property__c>();

        for (Home_Improvement__c homeimp : homeImprovements) {
            ids.add(homeimp.Property__c);
        }
        for (Property__c prop : [SELECT Id,SUM_of_Improvements__c, (SELECT Id, Amount__c FROM Home_Improvements__r) FROM Property__c WHERE Id = :ids]) {
            Decimal Sum = 0;
            for (Home_Improvement__c p : prop.Home_Improvements__r) {
                Sum = Sum + p.Amount__c ;
            }
            prop.SUM_of_Improvements__c = Sum;
            properties.add(prop);
        }
        try {
            update properties ;
        } catch (Exception e) {
            System.debug('Exception :' + e.getMessage());
        }
    }
}