src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Bill_To_Tenant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bill To Tenant</label>
        <referenceTo>Tenant__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>OF-{0000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Property__c.object
<CustomObject>
    <fields>
        <fullName>Business__c</fullName>
        <description>Business company or vendor renting the property</description>
        <label>Business</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Tenant__c.object
<CustomObject>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Tenants</relationshipLabel>
        <relationshipName>Tenants</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Rent_Due_Date__c</fullName>
        <label>Rent Due Date</label>
        <type>Date</type>
    </fields>
    <label>Tenant</label>
    <nameField>
        <label>Tenant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tenants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/InvoiceGenerateBatchTest.cls
/**
 * Created by Asel on 3/28/20.
 */

@IsTest
private class InvoiceGenerateBatchTest {

    @TestSetup
    static void setupData() {

        List<Property__c> prop = new List<Property__c>();
        Property__c property = new Property__c();
        property.Name = 'Prop1';
        property.Business__c = 'Gov';
        prop.add(property);
        insert prop;

        List<Tenant__c> ten = new List<Tenant__c>();
        Tenant__c tenant = new Tenant__c();
        tenant.Name = 'TenOne';
        tenant.Rent_Due_Date__c = System.today();
        tenant.Property__c = property.Id;
        ten.add(tenant);
        insert ten;

        }

    @IsTest
     static void testInvoiceGenerateBatch() {

     String CRON_EXP = '0 0 23 30 3 ?';
     Date dueDate = Date.today();

     Test.startTest();

     String jobId = System.schedule('CreateInvoice', CRON_EXP, new InvoiceGenerateBatchScheduled());
     Database.executeBatch(new InvoiceGenerateBatchJob());

     Test.stopTest();

     System.assertEquals(1, [SELECT Id FROM Invoice__c WHERE Bill_To_Tenant__r.Name = 'TenOne'].size());

        }
    }