src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Bill_To_Tenant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bill To Tenant</label>
        <referenceTo>Tenant__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>OF-{0000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Property__c.object
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Tenant__c.object
<CustomObject>
    <fields>
        <fullName>Monthly_Rate__c</fullName>
        <label>Monthly Rate</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Tenants</relationshipLabel>
        <relationshipName>Tenants</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Rent_Due_Date__c</fullName>
        <label>Rent Due Date</label>
        <type>Date</type>
    </fields>
    <label>Tenant</label>
    <nameField>
        <label>Tenant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tenants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/InvoiceCreateProcessSchedulable.cls
global class InvoiceCreateProcessSchedulable implements Schedulable{                                               // this class will generate invoices
                                                                                                        // for tenants whose payment date is today
    global Database.QueryLocator start(SchedulableContext ctx) {

        return Database.getQueryLocator([SELECT Name, Rent_Due_Date__c, Property__c, Monthly_Rate__c    // query for all tenants whose rent is due today
        FROM Tenant__c
        WHERE Rent_Due_Date__c = TODAY]);
    }

    global void execute(SchedulableContext ctx, List<Tenant__c> tenants) {                              // generate an invoice for each tenant
                                                                                                        // whose rent is due today
        List<Invoice__c> newInvoices = new List<Invoice__c>();                                          //create a List for Invoices.

        for (Tenant__c tenant : tenants) {
            Invoice__c inv          = new Invoice__c();
            inv.Bill_To_Tenant__c   = tenant.Name;
            inv.Bill_To_Tenant__c   = tenant.Id;

            insert inv;
        }
    }

    global void finish (SchedulableContext ctx){

    }

    global void execute(SchedulableContext param1) {

    }
}