src/objects/Invoice__c.object
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>OF-{0000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Property__c.object
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Tenant__c.object
<CustomObject>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Tenants</relationshipLabel>
        <relationshipName>Tenants</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Tenant</label>
    <nameField>
        <label>Tenant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tenants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/InvoiceCreateProcessTest.cls
/**
 * Created by Asel on 3/27/20.
 */

@IsTest
private class InvoiceCreateProcessTest {

    public static String CRON_EXP = '0 0 19 28 3 ?';

    @IsTest
    static void testScheduledJob(){

        List<Tenant__c> tenants = new List<Tenant__c>();
        Date dueDate = Date.today();

        for (Integer i = 1; i < 10; i++);{

            try {
                Tenant__c t = new Tenant__c();
                t.Name = 'TenOne';
                t.Property__c = [SELECT Id
                                 FROM Property__c
                                 WHERE Name = '48 Brattle st'
                                 LIMIT 10].Id;
                tenants.add(t);
            }
            catch (Exception e){

                insert tenants;

                Map<Id, Tenant__c> tenMap = new Map<Id, Tenant__c> (tenants);
                List<Id> tenIds = new List<Id>(tenMap.keySet());

                Test.startTest();
                String jobId = System.schedule('ScheduleApexTest', CRON_EXP, new InvoiceCreateProcessSchedulable());
                List<Invoice__c> invoices = [SELECT Id FROM Invoice__c WHERE Name IN:tenIds];
                System.assertEquals(0, tenants.size());
                Test.stopTest();

                invoices = [SELECT Id FROM Invoice__c WHERE Name IN :tenIds LIMIT 10];
                System.assertEquals(tenIds.size(), invoices.size(), 'Bills were not created');
            }
        }
    }
}