src/objects/Property__c.object
<CustomObject>
    <fields>
        <fullName>Average_Utilities__c</fullName>
        <label>Average Utilities</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Business__c</fullName>
        <description>Business company or vendor renting the property</description>
        <label>Business</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Utility__c.object
<CustomObject>
    <fields>
        <fullName>Amount_Paid__c</fullName>
        <label>Amount Paid</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Utilities</relationshipLabel>
        <relationshipName>Utilities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Utility</label>
    <nameField>
        <label>Utility Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utilities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AvgUtilityCalculationTest.cls
/**
 * Created by Asel on 3/27/20.
 */

@IsTest
private class AvgUtilityCalculationTest {

    @IsTest
    static void avgUtilityCalcTest() {

        Property__c prop = new Property__c();
        prop.Name        = '48 Brattle st';
        prop.Business__c = 'Gov';

        insert prop;

        Utility__c ut1     = new Utility__c();
        ut1.Name           = 'Gas';
        ut1.Property__c    = prop.Id;
        ut1.Amount_Paid__c = 150;

        insert ut1;

        Utility__c ut2     = new Utility__c();
        ut2.Name           = 'Water';
        ut2.Property__c    = prop.Id;
        ut2.Amount_Paid__c = 200;

        insert ut2;

        List<Property__c> properties = [
                SELECT Name, Average_Utilities__c
                FROM Property__c
                WHERE Name = '48 Brattle st'
        ];
        for (Property__c p : properties) {

            System.assertEquals(175, p.Average_Utilities__c);

        }

    }

}