src/objects/Property__c.object
<CustomObject>
    <fields>
        <fullName>Business__c</fullName>
        <description>Business company or vendor renting the property</description>
        <label>Business</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Tenant__c.object
<CustomObject>
    <fields>
        <fullName>Move_Out_Date__c</fullName>
        <label>Move Out Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Tenants</relationshipLabel>
        <relationshipName>Tenants</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Tenant</label>
    <nameField>
        <label>Tenant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tenants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/FOBCalloutSchedulableTest.cls
/**
 * Created by Asel on 4/3/20.
 */

@IsTest
private class FOBCalloutSchedulableTest {

    public static String CRON_EXP = '0 0 20 3 4 ?';
    Date dueDate = Date.today();

    @IsTest
    static void testScheduledJob() {

        Property__c property = new Property__c();
        property.Name = '48 Brattle st';
        property.Business__c = 'Gov';
        insert property;

        List<Tenant__c> tenants = new List<Tenant__c>();
        Tenant__c tenant = new Tenant__c();
        tenant.Name = 'TenOne';
        tenant.Property__c = property.Id;
        tenant.Move_Out_Date__c = System.today();
        tenants.add(tenant);
        insert tenants;

        Map<Id, Tenant__c> tenMap = new Map<Id, Tenant__c> (tenants);
        List<Id> tenIds = new List<Id>(tenMap.keySet());

        Test.startTest();
        String jobId = System.schedule('ScheduledFOBTest', CRON_EXP, new FOBCalloutsSchedulable());
        List<Tenant__c> tenants2 = [SELECT Name, Move_Out_Date__c, Property__c FROM Tenant__c WHERE Move_Out_Date__c = TODAY];
        System.assertEquals(1, tenants2.size());
        Test.stopTest();

    }
}