src/objects/Property__c.object
<CustomObject>
    <fields>
        <fullName>Business__c</fullName>
        <description>Business company or vendor renting the property</description>
        <label>Business</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <description>Individual person renting property</description>
        <label>Contact</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FieldnotEmptycontrl.cls
public with sharing class FieldnotEmptycontrl {
    public static void fieldNotEmpty(List<Property__c> prop) {

        for (Property__c property : prop) {
            //if both fields are empty the error message shows up
            if (property.Business__c == null && property.Contact__c == null) {

                property.Business__c.addError('Please enter a value in Business or Contact!');
                property.Contact__c.addError('Please enter a value in Business or Contact!');
            }
            //if both fields are not empty the error message shows up
            if (property.Business__c != null && property.Contact__c != null) {

                property.Business__c.addError('Cannot use two fields at the same time. Please choose only one field Business or Contact');
                property.Contact__c.addError('Cannot use two fields at the same time. Please choose only one field Business or Contact');
            }
        }
    }
}