src/objects/Property__c.object
<CustomObject>
    <fields>
        <fullName>Average_Utilities__c</fullName>
        <label>Average Utilities</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Utility__c.object
<CustomObject>
    <fields>
        <fullName>Amount_Paid__c</fullName>
        <label>Amount Paid</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Utilities</relationshipLabel>
        <relationshipName>Utilities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Utility</label>
    <nameField>
        <label>Utility Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utilities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AvgUtilityCalculation.cls
/**
 * Created by Asel on 3/25/20.
 */

public with sharing class AvgUtilityCalculation {
    public static void avgUtility(List<Utility__c> utilities) {

        Set<Id> propertyIds          = new Set<Id>();
        List<Property__c> properties = new List<Property__c>();

        //List<Utility__c> utilities   = Trigger.isInsert || Trigger.isUpdate ? Trigger.new : Trigger.old;

        for (Utility__c utl : utilities) {
            propertyIds.add(utl.Property__c);
        }

        for (AggregateResult agr : [
                SELECT Property__c, AVG(Amount_Paid__c) avg1
                FROM Utility__c
                GROUP BY Property__c
        ]) {

            properties.add(new Property__c(Id = (Id) agr.get('Property__c'),
                    Average_Utilities__c = (Decimal) agr.get('avg1')));

        }

        if (properties.size() > 0) {
            update properties;

        }
    }

}