src/objects/Property__c.object
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Tenant__c.object
<CustomObject>
    <fields>
        <fullName>Move_Out_Date__c</fullName>
        <label>Move Out Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Tenants</relationshipLabel>
        <relationshipName>Tenants</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Tenant</label>
    <nameField>
        <label>Tenant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tenants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/FOBCalloutBatchJob.cls
/**
 * Created by Asel on 4/3/20.
 */
global class FOBCalloutBatchJob implements Database.Batchable<SObject>{

    global Database.QueryLocator start(Database.BatchableContext BC){

    return Database.getQueryLocator([
            SELECT Name, Id, Move_Out_Date__c, Property__c
            FROM Tenant__c
            WHERE Move_Out_Date__c = TODAY
    ]);

    }

    global void execute(Database.BatchableContext BC, List<Tenant__c> tenants) {

        for (Tenant__c ten : tenants){
                if(ten.Move_Out_Date__c == System.today()) {
                    FOBCallouts.makePostCallout();
           }
        }
    }

    global void finish(Database.BatchableContext BC) {
    }

}